// Generated by dust2 (version 0.2.1) - do not edit

// Generated by odin2 (version 0.1.10) - do not edit
#include <dust2/common.hpp>
// [[dust2::class(ab_odin)]]
// [[dust2::time_type(discrete)]]
class ab_odin {
public:
  ab_odin() = delete;
  using real_type = double;
  using rng_state_type = monty::random::generator<real_type>;
  struct shared_state {
    struct dim_type {
      dust2::array::dimensions<1> rs;
      dust2::array::dimensions<1> rl;
      dust2::array::dimensions<1> dose_timesteps;
      dust2::array::dimensions<1> prop_short;
      dust2::array::dimensions<1> init_titres;
      dust2::array::dimensions<1> dose_index;
    } dim;
    struct offset_type {
      struct {
        size_t S;
        size_t L;
        size_t ab;
        size_t ps;
        size_t it;
      } state;
    } offset;
    std::vector<real_type> rs;
    std::vector<real_type> rl;
    std::vector<real_type> dose_timesteps;
    std::vector<real_type> prop_short;
    std::vector<real_type> init_titres;
    std::vector<real_type> dose_index;
    dust2::interpolate::InterpolateConstant<real_type> interpolate_dix;
  };
  struct internal_state {};
  using data_type = dust2::no_data;
  static dust2::packing packing_state(const shared_state& shared) {
    return dust2::packing{
      {"S", {}},
      {"L", {}},
      {"ab", {}},
      {"ps", {}},
      {"it", {}}
    };
  }
  static dust2::packing packing_gradient(const shared_state& shared) {
    return dust2::packing{
    };
  }
  static shared_state build_shared(cpp11::list parameters) {
    const auto dim_rs = dust2::r::read_dimensions<1>(parameters, "rs");
    const auto dim_rl = dust2::r::read_dimensions<1>(parameters, "rl");
    const auto dim_dose_timesteps = dust2::r::read_dimensions<1>(parameters, "dose_timesteps");
    const auto dim_prop_short = dust2::r::read_dimensions<1>(parameters, "prop_short");
    const auto dim_init_titres = dust2::r::read_dimensions<1>(parameters, "init_titres");
    const auto dim_dose_index = dust2::r::read_dimensions<1>(parameters, "dose_index");
    std::vector<real_type> rs(dim_rs.size);
    dust2::r::read_real_array(parameters, dim_rs, rs.data(), "rs", true);
    std::vector<real_type> rl(dim_rl.size);
    dust2::r::read_real_array(parameters, dim_rl, rl.data(), "rl", true);
    std::vector<real_type> dose_timesteps(dim_dose_timesteps.size);
    dust2::r::read_real_array(parameters, dim_dose_timesteps, dose_timesteps.data(), "dose_timesteps", true);
    std::vector<real_type> prop_short(dim_prop_short.size);
    dust2::r::read_real_array(parameters, dim_prop_short, prop_short.data(), "prop_short", true);
    std::vector<real_type> init_titres(dim_init_titres.size);
    dust2::r::read_real_array(parameters, dim_init_titres, init_titres.data(), "init_titres", true);
    std::vector<real_type> dose_index(dim_dose_index.size);
    dust2::r::read_real_array(parameters, dim_dose_index, dose_index.data(), "dose_index", true);
    const auto interpolate_dix = dust2::interpolate::InterpolateConstant(dose_timesteps, dose_index, "dose_timesteps", "dose_index");
    const shared_state::dim_type dim{dim_rs, dim_rl, dim_dose_timesteps, dim_prop_short, dim_init_titres, dim_dose_index};
    shared_state::offset_type offset;
    offset.state.S = 0;
    offset.state.L = 1;
    offset.state.ab = 2;
    offset.state.ps = 3;
    offset.state.it = 4;
    return shared_state{dim, offset, rs, rl, dose_timesteps, prop_short, init_titres, dose_index, interpolate_dix};
  }
  static internal_state build_internal(const shared_state& shared) {
    return internal_state{};
  }
  static void update_shared(cpp11::list parameters, shared_state& shared) {
    dust2::r::read_real_array(parameters, shared.dim.rs, shared.rs.data(), "rs", false);
    dust2::r::read_real_array(parameters, shared.dim.rl, shared.rl.data(), "rl", false);
    dust2::r::read_real_array(parameters, shared.dim.dose_timesteps, shared.dose_timesteps.data(), "dose_timesteps", false);
    dust2::r::read_real_array(parameters, shared.dim.prop_short, shared.prop_short.data(), "prop_short", false);
    dust2::r::read_real_array(parameters, shared.dim.init_titres, shared.init_titres.data(), "init_titres", false);
    dust2::r::read_real_array(parameters, shared.dim.dose_index, shared.dose_index.data(), "dose_index", false);
    const auto interpolate_dix = dust2::interpolate::InterpolateConstant(shared.dose_timesteps, shared.dose_index, "dose_timesteps", "dose_index");
  }
  static void update_internal(const shared_state& shared, internal_state& internal) {
  }
  static void initial(real_type time, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state) {
    state[0] = 0;
    state[1] = 0;
    state[2] = shared.init_titres[0];
    state[3] = shared.prop_short[0];
    state[4] = shared.init_titres[0];
  }
  static void update(real_type time, real_type dt, const real_type* state, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state_next) {
    const auto S = state[0];
    const auto L = state[1];
    const auto ps = state[3];
    const auto it = state[4];
    const real_type dix = shared.interpolate_dix.eval(time);
    const real_type p_s = 1 - monty::math::exp(-shared.rs[dix - 1] * dt);
    const real_type p_l = 1 - monty::math::exp(-shared.rl[dix - 1] * dt);
    const real_type n_s = monty::random::binomial<real_type>(rng_state, S, p_s);
    const real_type n_l = monty::random::binomial<real_type>(rng_state, L, p_l);
    state_next[0] = (time == shared.dose_timesteps[dix - 1] ? 1 : S - n_s);
    state_next[1] = (time == shared.dose_timesteps[dix - 1] ? 1 : L - n_l);
    state_next[3] = shared.prop_short[dix - 1];
    state_next[4] = (time == shared.dose_timesteps[dix - 1] ? monty::math::max(shared.init_titres[dix - 1], it * (ps * S + (1 - ps) * L)) : it);
    state_next[2] = it * (ps * S + (1 - ps) * L);
  }
  static auto zero_every(const shared_state& shared) {
    return dust2::zero_every_type<real_type>();
  }
};

#include <cpp11.hpp>
#include <dust2/r/discrete/system.hpp>

[[cpp11::register]]
SEXP dust2_system_ab_odin_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads) {
  return dust2::r::dust2_discrete_alloc<ab_odin>(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads);
}
[[cpp11::register]]
SEXP dust2_system_ab_odin_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_run_to_time<dust2::dust_discrete<ab_odin>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_ab_odin_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_state<dust2::dust_discrete<ab_odin>>(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_system_ab_odin_time(cpp11::sexp ptr) {
  return dust2::r::dust2_system_time<dust2::dust_discrete<ab_odin>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_ab_odin_set_state_initial(cpp11::sexp ptr) {
  return dust2::r::dust2_system_set_state_initial<dust2::dust_discrete<ab_odin>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_ab_odin_set_state(cpp11::sexp ptr, cpp11::list r_state) {
  return dust2::r::dust2_system_set_state<dust2::dust_discrete<ab_odin>>(ptr, r_state);
}

[[cpp11::register]]
SEXP dust2_system_ab_odin_reorder(cpp11::sexp ptr, cpp11::integers r_index) {
  return dust2::r::dust2_system_reorder<dust2::dust_discrete<ab_odin>>(ptr, r_index);
}

[[cpp11::register]]
SEXP dust2_system_ab_odin_rng_state(cpp11::sexp ptr) {
  return dust2::r::dust2_system_rng_state<dust2::dust_discrete<ab_odin>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_ab_odin_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state) {
  return dust2::r::dust2_system_set_rng_state<dust2::dust_discrete<ab_odin>>(ptr, r_rng_state);
}

[[cpp11::register]]
SEXP dust2_system_ab_odin_set_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_set_time<dust2::dust_discrete<ab_odin>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_ab_odin_update_pars(cpp11::sexp ptr, cpp11::list pars) {
  return dust2::r::dust2_system_update_pars<dust2::dust_discrete<ab_odin>>(ptr, pars);
}

[[cpp11::register]]
SEXP dust2_system_ab_odin_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_simulate<dust2::dust_discrete<ab_odin>>(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension);
}
