# Generated by cpp11: do not edit by hand

ab_cpp <- function(t, dose_timesteps, init_titres, prop_short, dur_short, dur_long) {
  .Call(`_boostr_ab_cpp`, t, dose_timesteps, init_titres, prop_short, dur_short, dur_long)
}

efficacy_cpp <- function(titre, max_efficacy, alpha, beta) {
  .Call(`_boostr_efficacy_cpp`, titre, max_efficacy, alpha, beta)
}
