## Generated by dust2 (version 0.2.1) - do not edit
ab_odin <- structure(
  function() get("ab_odin"),
  class = "dust_system_generator",
  name = "ab_odin",
  properties = list(
    time_type = "discrete",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = 1)
